pipeline {
    agent any
    environment {
        DOCKER_CREDENTIALS_ID = 'jenkins-docker'  // Docker credentials ID from Jenkins credentials
    }
    stages {
        stage('Build and Push Docker Images') {
            steps {
                script {
                    // Run build_push.sh from the jenkins directory
                    dir('jenkins') {
                        sh './build_push.sh'
                    }
                }
            }
        }
        stage('Deploy to Minikube') {
            steps {
                script {
                    // Deploy backend
                    sh 'kubectl apply -f backend/deployment.yaml'

                    // Deploy frontend
                    sh 'kubectl apply -f frontend/deployment.yaml'

                    // Deploy database
                    sh 'kubectl apply -f database/deployment.yaml'
                }
            }
        }
    }
}
